---
title: "Homework 6: Spatial Dashboard"
author: "Santiago Charry"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include = FALSE, echo = FALSE}

library(plotly)
library(flexdashboard)



#Working directory for .RMD
knitr::opts_knit$set(echo = TRUE,
                     root.dir = rprojroot::find_rstudio_root_file())

#Controlling figure output in markdown
knitr::opts_chunk$set(
#  fig.height =   
  fig.width = 6,
#  fig.asp = .5,
  out.width = "90%",
#  out.height = 
 fig.align  = "center",
  cache = FALSE,
  eval  = TRUE,
  echo  = FALSE,
  warning = FALSE
)

#My Colours (from viridis)
my_purple <- "#440154FF"
my_yellow <- "#FDE725FF"

#Set Theme for ggplot2
theme_set(theme_bw() + theme(plot.title = element_text(hjust = 0.5), legend.position = "bottom"))

#Set Scientific notation output and decimal places for knitr
options(scipen = 999)
options(digits = 4)
options(dplyr.summarise.inform = FALSE)
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
library(ggthemes)
library(sf)
library(ggmap)
library(tmap)
library(tidycensus)
library(leaflet)
library(osmdata)
library(tigris)
library(tidyr)
library(dplyr)
library(forcats)
library(stringr)
library(gt)
library(purrr)
library(plotly)

#ASSIGNMENT 8: load in census API key
api_key <- Sys.getenv("MAPS_API_KEY")
census_api_key(api_key)

#Let's grab the liquor stores and hunting stores
osm_shop_sf.df <- opq(bbox = "hennepin") %>%
  add_osm_feature(key = "shop", value = c("coffee", "bakery", "gift")) %>%
  osmdata_sf()

#Extract the relevent sf data frame
shop_points.df <- osm_shop_sf.df$osm_points %>% 
  janitor::clean_names() %>%
  filter(!is.na(shop)) %>% #only retain 'valid' tags
  dplyr::select(osm_id, name, shop, opening_hours, phone, website, geometry) %>%
  mutate(shop = str_to_title(shop) %>% as_factor())

#manually creating bounding boxes
mn.box <- matrix(c(-97.24, 43.50, -89.48, 49.38),
                     ncol  = 2,
                     byrow = TRUE)
colnames(mn.box) <- c("min", "max")
rownames(mn.box) <- c("x", "y")

hennepin.box <- matrix(c(-93.77, 44.79, -93.18, 45.25),
                     ncol  = 2,
                     byrow = TRUE)
colnames(hennepin.box) <- c("min", "max")
rownames(hennepin.box) <- c("x", "y")


#Get the bounding box and county outline
#mn.box           <- osmdata::getbb("minnesota")
#hennepin.box     <- osmdata::getbb("hennepin")
hennepin.outline <- osmdata::getbb("hennepin", format_out = "polygon")[[1]] %>%
  as_tibble() %>%
  rename(longitude = V1, latitude = V2)

#Get the base map (foundational layer)
mn_base.map <- get_map(
  location = hennepin.box,
  source   = "stamen",
  maptype  = "terrain",
  crop = TRUE
)

hennepin_base.gg <- ggmap(mn_base.map) +
  geom_polygon(data = hennepin.outline, aes(x = longitude, y = latitude), colour = "black", size = 1.6, alpha = 0.1) +
  theme_map() +
  theme(
    plot.title   = element_text(size  = 16,
                                hjust = 0.5),
    legend.text  = element_text(size = 16),
    legend.title = element_text(size = 16),
    legend.position = "right"
  )


#Call viridis library  
library(viridis, quietly = TRUE)

#Extract the levels/order of shop type factor
shop_types <- levels(shop_points.df$shop)
n_types    <- length(shop_types)

#Initialize our colour pallete (discrete in this case)
my_pallete <- colorFactor(viridis_pal(option = "D")(n_types), levels = shop_types)

#Need html tools to get our labels to render appropriately
library(htmltools, quietly = TRUE)

#Add a text label like normal
shop_label.df <- shop_points.df %>%
  mutate(
    across(
      c(name, opening_hours:website),
      ~ifelse(is.na(.x), "NA", .x)
    ),
    text_label = str_c(
      name,
      "<br/>Store Type: ",
      shop,
      "<br/>Open Hours: ",
      opening_hours,
      "<br/>Phone: ",
      phone,
      "<br/>Website: ",
      website
    )
  )

shop_label.df %>%
  leaflet() %>%
  addProviderTiles('CartoDB.Positron') %>% 
  addCircleMarkers(
    color   = ~my_pallete(shop),
    label   = ~map(text_label, HTML), #map over labels, make html
    opacity = 0.6, #alpha
    weight  = 4, #outline strength
    radius  = 4 #size of circle
  ) %>%
  addLegend(
    title    = "Store Type",
    position = "bottomright",
    colors   = viridis_pal(option = "D")(n_types),
    labels   = shop_types 
  )
```

Column {data-width=600}
-----------------------------------------------------------------------

```{r include=FALSE}
HC_gini.df <- get_acs(
  geography = "tract",
  variables = "B19083_001", #Code for gini index
  state     = "MN",
  county    = "Hennepin",
  year      = 2020,
  geometry  = TRUE)

HC_gini_plotly.df <- HC_gini.df %>%
  mutate(
    tract      = str_split(NAME, ",") %>%
      map_chr(1) %>%
      str_remove("Census Tract "),
    text_label = str_c(
      "Tract: ",
      tract,
      "\nGini: ",
      (estimate)
    )
  )

gini.gg <- ggplot() +
  geom_sf(data = HC_gini.df, aes(fill = estimate)) +
  labs(title = "Hennepin County 2020 ACS Estimated Gini Index", subtitle = "Where 0.3 indicates reasonable income gap and >0.5 indicates severe income disparity") +
  theme_void() +
  scale_fill_viridis_c("Gini Index")+
  theme_map() +
  theme(
    plot.title   = element_text(size  = 16,
                                hjust = 0.5),
    legend.text  = element_text(size = 16),
    legend.title = element_text(size = 16),
    legend.position = "right"
  )

ggplotly(gini.gg,
         data=HC_gini_plotly.df,
         tooltip = "text_label",
         height  = 600,
         width   = 800) %>%
  style(hoveron = "fills")
# 
# #ggmap example 3
mn.box           <- osmdata::getbb("minnesota")
hennepin.box     <- osmdata::getbb("hennepin")
hennepin.outline <- osmdata::getbb("hennepin", format_out = "polygon")[[1]] %>%
  as_tibble() %>%
  rename(longitude = V1, latitude = V2)

mn_base.map <- get_map(
  location = hennepin.box,
  source   = "stamen",
  maptype  = "terrain",
  crop = TRUE
)

hennepin_base.gg <- ggmap(mn_base.map) +
  geom_polygon(data = hennepin.outline, aes(x = longitude, y = latitude), colour = "black", size = 1.6, alpha = 0.1) +
  theme_map() +
  theme(
    plot.title   = element_text(size  = 16,
                                hjust = 0.5),
    legend.text  = element_text(size = 16),
    legend.title = element_text(size = 16),
    legend.position = "right"
  )

coord_ggmap <- st_crs(hennepin_base.gg) #NA
coord_sf    <- st_crs(HC_gini_plotly.df) #NAD83

mn_gini.ggmap <- hennepin_base.gg +
  geom_sf(data = HC_gini_plotly.df,
          aes(fill = estimate, text = text_label),
          colour = "black", size = 0.1,
          inherit.aes = FALSE) +
  labs(title = "Hennepin County, MN 2020 ACS Gini Index") +
  scale_fill_viridis_c("Gini Index") +
  theme_map() +
  theme(
    plot.title   = element_text(size  = 16,
                                hjust = 0.5),
    legend.text  = element_text(size = 16),
    legend.title = element_text(size = 16),
    legend.position = "right"
  )
```


### Chart B

```{r}
ggplotly(mn_gini.ggmap,
         tooltip = "text",
         height  = 600,
         width   = 800) %>%
  style(hoveron = "fills")
```


```{r include=FALSE}
HC_rent.df <- get_acs(
  geography = "tract",
  variables = "B25064_001", #Code for educational attainment
  state     = "MN",
  county    = "Hennepin",
  year      = 2020,
  geometry  = TRUE)

HC_rent_plotly.df <- HC_rent.df %>%
  mutate(
    tract      = str_split(NAME, ",") %>%
      map_chr(1) %>%
      str_remove("Census Tract "),
    text_label = str_c(
      "Tract: ",
      tract,
      "\nMedian Rent: ",
      scales::dollar(estimate)
    )
  )

rent.gg <- ggplot() + 
  geom_sf(data = HC_rent.df, aes(fill = estimate)) + 
  labs(title = "Hennepin County 2020 Median Rent") + 
  theme_void() + 
  scale_fill_viridis_c("Median Rent", labels = scales::dollar)+
  theme_map() +
  theme(
    plot.title   = element_text(size  = 16,
                                hjust = 0.5),
    legend.text  = element_text(size = 16),
    legend.title = element_text(size = 16),
    legend.position = "right"
  )

#Display
rent.gg

ggplotly(rent.gg,
         data=HC_rent_plotly.df,
         tooltip = "text_label",
         height  = 600,
         width   = 800) %>%
  style(hoveron = "fills")

mn.box           <- osmdata::getbb("minnesota")
hennepin.box     <- osmdata::getbb("hennepin")
hennepin.outline <- osmdata::getbb("hennepin", format_out = "polygon")[[1]] %>%
  as_tibble() %>%
  rename(longitude = V1, latitude = V2)

mn_base.map <- get_map(
  location = hennepin.box,
  source   = "stamen",
  maptype  = "terrain",
  crop = TRUE
)

hennepin_base.gg <- ggmap(mn_base.map) +
  geom_polygon(data = hennepin.outline, aes(x = longitude, y = latitude), colour = "black", size = 1.6, alpha = 0.1) +
  theme_map() +
  theme(
    plot.title   = element_text(size  = 16,
                                hjust = 0.5),
    legend.text  = element_text(size = 16),
    legend.title = element_text(size = 16),
    legend.position = "right"
  )

hennepin_base.gg

coord_ggmap <- st_crs(hennepin_base.gg) #NA
coord_sf_rent    <- st_crs(HC_rent_plotly.df) #NAD83

mn_rent.ggmap <- hennepin_base.gg +  
  geom_sf(data = HC_rent_plotly.df, 
          aes(fill = estimate, text = text_label),
          colour = "black", size = 0.1,
          inherit.aes = FALSE) + 
  labs(title = "Hennepin County, MN 2020 Median Rent") + 
  scale_fill_viridis_c("Median Rent", labels = scales::dollar) +
  theme_map() +
  theme(
    plot.title   = element_text(size  = 16,
                                hjust = 0.5),
    legend.text  = element_text(size = 16),
    legend.title = element_text(size = 16),
    legend.position = "right"
  )

```

### Chart C

```{r}

ggplotly(mn_rent.ggmap,
         tooltip = "text",
         height  = 600,
         width   = 800) %>%
  style(hoveron = "fills")
```

