on:
  workflow_dispatch:
  
name: Render Report


jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    permissions:
        contents: write
    
    env:
      MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0' # The R version to download (if necessary) and use.
 
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
            packages:
               any::knitr
               any::rmarkdown
               any::jsonlite
               any::dplyr
               any::ggplot2
               any::readr
               any::lubridate
               any::forcats
               any::tidyverse
               any::data.table
               any::googledrive
               any::gt
               any::ggthemes
               any::sf
               any::ggmap
               any::tmap
               any::tidycensus
               any::leaflet
               any::osmdata
               any::tigris
               any::tidyr
               any::stringr
               any::purrr
               any::plotly
               any::flexdashboard
               any::viridis
               any::htmltools
               
       - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
            packages:
               any::knitr
               any::rmarkdown
               any::jsonlite
               any::dplyr
               any::ggplot2
               any::readr
               any::lubridate
               any::forcats
               any::tidyverse
               any::data.table
               any::googledrive
               any::gt
               any::ggthemes
               any::sf
               any::ggmap
               any::tmap
               any::tidycensus
               any::leaflet
               any::osmdata
               any::tigris
               any::tidyr
               any::stringr
               any::purrr
               any::plotly

      - name: Render document
        run: |
          R -e "rmarkdown::render('Assignment6_Charry.RMD', output_format = 'html_document')"
 
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Commit
        run: |
          git add .
          git commit -m "Updated report"
          git push origin main
